### PR TITLE
Port cookie banner

### PR DESCRIPTION
**Pull request by Pythonix**
Ports the cookie banner used on gridcoin.us (based on https://github.com/gridcoin-community/Gridcoin-Site/pull/301).

image

### CODE REVIEW

**Comment by barton2526** [comment]
Is cloudflare even used on this site?

**Comment by Pythonix** [comment]
> Is cloudflare even used on this site?

You're right. I removed all mentions of cloudflare and the cookie banner is only shown if DNT is not enabled.

**Comment by RoboticMind** [comment]
Should probably bring this over to the new repo on Gridcoin-Community https://github.com/gridcoin-community/Gridcoin-World-Site

**Comment by Pythonix** [comment]
> Should probably bring this over to the new repo on Gridcoin-Community https://github.com/gridcoin-community/Gridcoin-World-Site

Done: https://github.com/gridcoin-community/Gridcoin-World-Site/pull/2

**Pull request closed without merging**
